# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bifrost < Formula
  desc "SSH/SFTP Connection Manager"
  homepage "https://github.com/steevenmentech/bifrost"
  version "0.0.3"
  license "Non-Commercial"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steevenmentech/bifrost/releases/download/v0.0.3/bifrost_0.0.3_darwin_amd64.tar.gz"
      sha256 "9fb177609eb315cc4781454dfa14310b48e5a5edb75a4dde23b8710aa40b3c29"

      def install
        bin.install "bifrost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steevenmentech/bifrost/releases/download/v0.0.3/bifrost_0.0.3_darwin_arm64.tar.gz"
      sha256 "26c4efc7bef499aeec68185ed32cef71f7921d893eda7320e226b2a16adffd78"

      def install
        bin.install "bifrost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/steevenmentech/bifrost/releases/download/v0.0.3/bifrost_0.0.3_linux_amd64.tar.gz"
      sha256 "e9c577e1dc223d6b9253af85e71628577354a2bc56dc20c849e51d94628289e5"
      def install
        bin.install "bifrost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steevenmentech/bifrost/releases/download/v0.0.3/bifrost_0.0.3_linux_arm64.tar.gz"
      sha256 "b70821c58d97b12c7dd5f990b000e065044029095d1c6e1eba01d8393dc2407c"
      def install
        bin.install "bifrost"
      end
    end
  end

  test do
    system "#{bin}/bifrost", "--version"
  end
end
